// 석판(키워드) 해석기 회귀 시험: 새 플레이어가 쓸 법한 문장과 기대하는 행동
//   node tools/tests/tablet-cases.mjs [--all]
// 판정: want의 행동 종류(gather:any는 아무 채집)가 모두 나오고(금지는 forbid), avoid에 적힌 종류는 나오지 않아야 "성공".
// 상태: 튜토리얼 3×3 1장 (율법파 마을이 바로 옆이라 선교·공격 대상이 있다)
import * as E from '../../js/game/engine.js';
import * as I from '../../js/game/interpreter.js';

// 행동 종류 표기: gather:food / gather:wood / gather:stone / build:village / build:wall / build:temple / pray / explore / preach / attack
const CASES = [
  ['강에서 물고기를 잡고 이웃에게 사랑을 전하라', ['preach'], []],
  ['식량을 모아라', ['gather:food'], []],
  ['배불리 먹고 번성하라', ['gather:food'], []],
  ['나무를 베어 집을 지어라', ['gather:wood', 'build:village'], []],
  ['집을 더 지어라', ['build:village'], []],
  ['적을 물리쳐라', ['attack'], []],
  ['율법파를 공격하라', ['attack'], []],
  ['싸워라', ['attack'], []],
  ['전쟁을 준비하라', ['attack'], []],
  ['적의 마을을 빼앗아라', ['attack'], ['build:village']],
  ['신전에서 기도하라', ['pray'], []],
  ['기도해라', ['pray'], []],
  ['안개 너머를 살펴보라', ['explore'], []],
  ['세상을 둘러보라', ['explore'], []],
  ['새 땅을 개척하라', ['build:village'], []],
  ['겨울이 온다', ['gather:food'], []],
  ['바람이 부는 쪽으로 가라', ['explore'], []],
  ['굶주린 자가 없게 하라', ['gather:food'], []],
  ['돌을 모아 성벽을 쌓아라', ['gather:stone'], []],
  ['너희는 강하고 담대하라', [], ['gather:food']],
  ['산에 올라 나를 경배하라', ['pray'], []],
  ['아이를 많이 낳아 번성하라', ['build:village'], []],
  ['돌아가서 기다려라', [], ['gather:stone']],
  ['숲을 베지 말고 산에서 돌을 캐라', ['gather:stone', 'forbid:gather:wood'], ['gather:wood']],
  ['서로 사랑하라', ['preach'], []],
  ['빛이 있으라', ['explore'], []],
  ['오늘은 푹 쉬어라', ['pray'], []],
  ['곡식을 거두고 나무를 베고 돌을 캐라', ['gather:food', 'gather:wood', 'gather:stone'], []],
  ['불로 심판하라', ['attack'], []],
  ['그들을 쳐부숴라', ['attack'], []],
  ['자원을 최대한 모아라', ['gather:any'], []],
  ['생산을 늘려라', ['gather:any'], []],
  ['가서 너의 동족을 설득하라', ['preach'], []],
  ['나를 믿으라', ['pray'], []],
  ['지켜보라, 내가 기적을 행하리라', [], ['build:wall']],
  ['사자처럼 용맹하게 싸우라', ['attack'], []],
  ['두려워하지 말고 쳐라', ['attack'], []],
  ['곡식을 많이 거두라', ['gather:food'], []],
  ['마을마다 성벽을 쌓아 지켜라', ['build:wall'], []],
  ['율법파의 땅에 말씀을 전하라', ['preach'], ['build:village']],
  // 새 문장 시험 묶음 1~3 (2026-09-30). 묶음 3의 첫 측정(튜닝 전)은 67%였다
  ['들판의 곡식을 거둬들여라', ['gather:food'], []],
  ['물가에서 고기를 낚아라', ['gather:food'], []],
  ['성을 쌓아 적을 막아라', ['build:wall'], []],
  ['적들을 몰아내라', ['attack'], []],
  ['이웃 부족과 화해하라', ['preach'], []],
  ['주님께 제물을 바쳐라', ['pray'], []],
  ['새로운 마을을 세워라', ['build:village'], []],
  ['높은 탑을 쌓아라', ['build:temple'], []],
  ['숲에서 땔감을 구하라', ['gather:wood'], []],
  ['돌을 깎아 신전을 높여라', ['build:temple'], []],
  ['모두 함께 밭을 갈아라', ['gather:food'], []],
  ['멀리 떨어진 땅을 알아보라', ['explore'], []],
  ['율법파에게 복음을 전하라', ['preach'], []],
  ['침략자를 쫓아내라', ['attack'], []],
  ['백성을 불려라', ['build:village'], []],
  ['곳간을 채워라', ['gather:food'], []],
  ['창을 들고 나아가라', ['attack'], []],
  ['신께 감사하라', ['pray'], []],
  ['저 산 너머에 무엇이 있는지 알아보라', ['explore'], []],
  ['배고픈 자에게 빵을 나눠라', ['gather:food'], []],
  ['나무를 심고 숲을 가꾸어라', ['gather:wood'], []],
  ['마을을 지키는 담을 쌓아라', ['build:wall'], []],
  ['율법의 탑을 무너뜨려라', ['attack'], []],
  ['평화롭게 지내라', ['pray'], []],
  ['땅을 넓혀 자손을 번성케 하라', ['build:village'], []],
  ['씨를 뿌리고 거두는 자가 되라', ['gather:food'], []],
  ['너희의 칼을 갈아라', ['attack'], []],
  ['모든 이에게 나의 뜻을 알려라', ['preach'], []],
  ['저들의 신전을 불살라라', ['attack'], ['build:temple']],
  ['들짐승을 사냥하라', ['gather:food'], []],
  ['강둑을 따라 마을을 세워라', ['build:village'], []],
  ['너희 신앙을 굳게 하라', ['pray'], []],
  ['나의 집을 크게 지어라', ['build:temple'], []],
  ['외지인을 받아들여라', ['preach'], []],
  ['곡간이 넘치게 하라', ['gather:food'], []],
  ['적의 성벽을 깨뜨려라', ['attack'], ['build:wall']],
  ['광야로 나가 길을 찾아라', ['explore'], []],
  ['나를 찬송하라', ['pray'], []],
  ['형제를 가르쳐라', ['preach'], []],
  ['바위를 깨어 돌을 모아라', ['gather:stone'], []],
  ['큰 나무를 베어 배를 만들어라', ['gather:wood'], []],
  ['이방인에게 나의 이름을 전파하라', ['preach'], []],
  ['밤이 오기 전에 창고를 채워라', ['gather:food'], []],
  ['적이 오면 맞서 싸워라', ['attack'], []],
  ['안식일을 지켜라', ['pray'], ['build:wall']],
  ['백성이 굶지 않게 하라', ['gather:food'], []],
  ['높은 곳에 제단을 쌓아라', ['build:temple'], []],
  ['먼 곳을 살피고 돌아오라', ['explore'], []],
  ['율법파의 마을로 진군하라', ['attack'], ['build:village']],
  ['새 터전을 마련하라', ['build:village'], []],
  ['성벽을 높이 쌓아라', ['build:wall'], ['build:temple']],
  ['함께 노래하며 기도하라', ['pray'], []],
  ['고기를 잡아 백성을 먹여라', ['gather:food'], []],
  ['어둠을 밝혀라', ['explore'], []],
  ['우리 땅을 굳게 지켜라', ['build:wall'], []],
  ['부지런히 일하여 먹을 것을 쌓아라', ['gather:food'], []],
  ['네 이웃을 네 몸같이 여겨라', ['preach'], []],
  ['원수를 갚아라', ['attack'], []],
  ['해가 뜨는 곳으로 떠나라', ['explore'], []],
  ['돌로 단을 쌓고 향을 피워라', ['pray'], []],
  ['숲속의 나무를 모두 베어라', ['gather:wood'], []],
  ['굳건한 성채를 세워라', ['build:wall'], []],
  ['나의 거룩한 집을 더 높여라', ['build:temple'], []],
  ['사람들이 모여 살 곳을 마련하라', ['build:village'], []],
  ['그들을 설득하여 우리 편으로 만들어라', ['preach'], []],
  ['가뭄이 오니 곡식을 아껴 거두라', ['gather:food'], []],
  ['하늘을 우러러 경배하라', ['pray'], []],
  ['모르는 땅을 밟아 보라', ['explore'], []],
  ['율법파를 벌하라', ['attack'], []],
  ['광산에서 돌을 캐내라', ['gather:stone'], []],
  ['울타리를 둘러 마을을 보호하라', ['build:wall'], []],
  ['후손이 많아지게 하라', ['build:village'], []],
  ['내게 무릎 꿇어라', ['pray'], []],
  ['물고기를 잡아 굶주림을 면하라', ['gather:food'], []],
  ['적진으로 쳐들어가라', ['attack'], []],
  ['나의 말을 온 세상에 퍼뜨려라', ['preach'], []],
  ['목재를 넉넉히 마련하라', ['gather:wood'], []],
  ['신전의 첨탑을 올려라', ['build:temple'], []],
  ['조용히 쉬며 나를 기억하라', ['pray'], []],
  ['낯선 곳의 비밀을 밝혀내라', ['explore'], []],
  ['그들의 마을을 불태워라', ['attack'], []],
  ['형제들을 불러 모아 함께 살게 하라', ['build:village'], []],
  ['열매를 따서 저장하라', ['gather:food'], []],
  ['의심하는 자들에게 가르침을 베풀라', ['preach'], []],
  ['방패를 들고 굳게 버텨라', ['build:wall'], []],
  // 묶음 4 — 첫 측정 77%
  ['밭을 일구어 양식을 마련하라', ['gather:food'], []],
  ['이웃과 빵을 나누며 복음을 들려주라', ['preach'], []],
  ['적의 진영을 급습하라', ['attack'], []],
  ['산에 가서 돌을 가져오라', ['gather:stone'], []],
  ['땔나무를 해 오너라', ['gather:wood'], []],
  ['자손을 퍼뜨려 땅에 가득하라', ['build:village'], []],
  ['너희 성을 튼튼히 하라', ['build:wall'], []],
  ['내 성소를 더 크게 하라', ['build:temple'], []],
  ['엎드려 절하라', ['pray'], []],
  ['안개 속 땅을 밝히러 가라', ['explore'], []],
  ['저들에게 나의 사랑을 보여라', ['preach'], []],
  ['칼을 뽑아 저들을 베어라', ['attack'], []],
  ['곡식이 익었으니 거둬라', ['gather:food'], []],
  ['새로운 정착지를 만들어라', ['build:village'], []],
  ['숲의 나무를 넉넉히 베어 오라', ['gather:wood'], []],
  ['돌을 깨서 쌓아 두라', ['gather:stone'], []],
  ['경계를 굳건히 하라', ['build:wall'], []],
  ['저녁마다 기도를 올려라', ['pray'], []],
  ['미지의 땅으로 발을 내디뎌라', ['explore'], []],
  ['율법에 묶인 자들을 풀어 주라', ['preach'], []],
  ['적의 마을을 점령하라', ['attack'], []],
  ['바다처럼 넓은 들판에서 추수하라', ['gather:food'], []],
  ['아이들이 뛰놀 마을을 지어라', ['build:village'], []],
  ['신전의 지붕을 높이 올려라', ['build:temple'], []],
  ['나를 경외하라', ['pray'], []],
  ['숨겨진 보물을 찾아라', ['explore'], []],
  ['원수를 사랑하라', ['preach'], []],
  ['그들의 탑을 쓰러뜨려라', ['attack'], []],
  ['물고기를 넉넉히 잡아라', ['gather:food'], []],
  ['창과 방패로 마을을 지켜라', ['build:wall'], []],
  // 묶음 5 — 은유 섞음, 첫 측정 68%
  ['주린 배를 채울 이삭을 모아라', ['gather:food'], []],
  ['바람을 막을 벽을 세워라', ['build:wall'], []],
  ['너희의 등불을 들고 어둠 속으로 들어가라', ['explore'], []],
  ['이웃의 마음을 얻어라', ['preach'], []],
  ['불의 심판을 내리리라', ['attack'], []],
  ['내 이름으로 탑을 세워 하늘에 닿게 하라', ['build:temple'], []],
  ['씨앗이 자라 숲이 되게 하라', ['gather:wood'], []],
  ['돌 위에 돌을 쌓아라', ['gather:stone'], []],
  ['자녀를 낳고 번성하여 땅을 채우라', ['build:village'], []],
  ['무릎을 꿇고 나를 부르라', ['pray'], []],
  ['저 너머 산등성이를 넘어가라', ['explore'], []],
  ['낯선 이를 형제로 맞으라', ['preach'], []],
  ['창을 벼리고 적을 무찔러라', ['attack'], []],
  ['곳간 가득 곡식을 채워라', ['gather:food'], []],
  ['나무를 다듬어 집을 지으라', ['gather:wood'], []],
  ['단단한 성곽으로 우리를 두르라', ['build:wall'], []],
  ['향기로운 제물을 올려라', ['pray'], []],
  ['목자처럼 흩어진 양을 모으라', ['preach'], []],
  ['강물이 너희를 먹이리라', ['gather:food'], []],
  ['율법의 요새를 허물어라', ['attack'], []],
  ['새벽에 일어나 나를 찬양하라', ['pray'], []],
  ['광야에 새 마을을 일으켜라', ['build:village'], []],
  ['깊은 숲에서 재목을 구하라', ['gather:wood'], []],
  ['채석장의 바위를 쪼개라', ['gather:stone'], []],
  ['눈을 들어 먼 곳을 보라', ['explore'], []],
  ['나의 전을 영화롭게 하라', ['build:temple'], []],
  ['칼날 위에 정의를 세우라', ['attack'], []],
  ['굶는 자에게 떡을 주라', ['gather:food'], []],
  ['울타리 안에 양 떼를 지켜라', ['build:wall'], []],
  ['화해의 손을 내밀라', ['preach'], []],
  ['침묵 속에서 나를 기다려라', ['pray'], []],
  ['잃어버린 땅을 되찾아라', ['attack'], []],
  ['너희 수를 늘려라', ['build:village'], []],
  ['안개를 걷어 내라', ['explore'], []],
  ['평원에 이삭이 넘치게 하라', ['gather:food'], []],
  ['신전 기둥을 더 세워라', ['build:temple'], []],
  ['적의 문을 두드려 부숴라', ['attack'], []],
  ['사랑으로 그들을 이겨라', ['preach'], []],
  ['산을 깎아 돌을 얻어라', ['gather:stone'], []],
  ['땅끝까지 가 보라', ['explore'], []],
  // 묶음 6 — 어휘를 보지 않은 에이전트가 씀, 첫 측정 90%
  ['벌목꾼들은 통나무를 잔뜩 해오너라', ['gather:wood'], []],
  ['밭에 나가 곡식을 거두어라', ['gather:food'], []],
  ['채석장에서 바위를 깨라', ['gather:stone'], []],
  ['새 마을을 세워라', ['build:village'], []],
  ['신전을 지어라', ['build:temple'], []],
  ['마을 둘레에 튼튼한 성벽을 쌓아라', ['build:wall'], []],
  ['율법파 사람들에게 사랑을 전하라', ['preach'], []],
  ['율법파의 땅을 공격하라', ['attack'], []],
  ['엎드려 기도하라', ['pray'], []],
  ['안개 너머 미지의 땅을 탐험하라', ['explore'], []],
  ['강가에서 물고기를 잡아 오너라', ['gather:food'], []],
  ['도끼를 들고 나무를 찍어 넘겨라', ['gather:wood'], []],
  ['돌을 캐서 창고에 쌓아 두어라', ['gather:stone'], []],
  ['빈 땅으로 이주하여 터전을 넓혀라', ['build:village'], []],
  ['예배를 드릴 성소를 세워라', ['build:temple'], []],
  ['적의 수도로 진격하여 쳐부숴라', ['attack'], []],
  ['율법파를 말로 설득하여 우리 신도로 만들어라', ['preach'], []],
  ['정찰병을 보내 저 너머를 살펴보아라', ['explore'], []],
  ['성물을 바쳐 제사를 올려라', ['pray'], []],
  ['방벽을 세워 외적의 침입에 대비하라', ['build:wall'], []],
  ['황금빛 물결치는 들녘의 수확을 백성에게 안겨라', ['gather:food'], []],
  ['불의 검을 들어 저 교만한 무리의 성을 무너뜨려라', ['attack'], []],
  ['푸른 숲의 어깨에서 향기로운 백향목을 내려받아라', ['gather:wood'], []],
  ['석공의 망치로 산의 심장을 두드려 단단한 반석을 얻어라', ['gather:stone'], []],
  ['하늘에 닿는 탑을 올려 내 이름을 기리라', ['build:temple'], []],
  ['여리고와 같은 견고한 성벽으로 백성의 잠자리를 감싸라', ['build:wall'], []],
  ['율법의 굴레에 갇힌 영혼들을 자비의 손길로 끌어안아라', ['preach'], []],
  ['가나안 같은 새 터에 우리의 천막을 치고 뿌리내려라', ['build:village'], []],
  ['영혼의 노래로 나의 이름을 높여 찬양하라', ['pray'], []],
  ['별빛을 길잡이 삼아 이름 없는 대지를 밟아라', ['explore'], []],
  ['굶주린 이들의 배를 광야의 만나로 채워라', ['gather:food'], []],
  ['톱질 소리로 숲의 고요를 깨워 우리 몫의 나무를 얻어라', ['gather:wood'], []],
  ['어둠 속 이리떼로부터 양 떼를 지킬 울타리를 두르라', ['build:wall'], []],
  ['번제의 연기를 올려 감사의 향기를 드려라', ['pray'], []],
  ['피의 값을 치르게 하라, 저들의 깃발을 짓밟아라', ['attack'], []],
  ['지평선 저편, 지도에 없는 곳으로 순례를 떠나라', ['explore'], []],
  ['들꽃이 번지듯 내 자녀들이 이 땅 곳곳에 새 보금자리를 이루게 하라', ['build:village'], []],
  ['지성소를 지어 나의 임재가 머물게 하라', ['build:temple'], []],
  ['형, 바위 좀 부숴서 돌 좀 모아봐', ['gather:stone'], []],
  ['저 율법파 놈들 한번 쳐들어가서 박살내자', ['attack'], []],
  ['배고파 죽겠다 뭐 좀 먹을 거 구해와', ['gather:food'], []],
  ['나무 좀 베어 와라 땔감이 없다', ['gather:wood'], []],
  ['다들 모여서 나한테 감사 인사나 좀 드려봐', ['pray'], []],
  ['저기 뭐 있나 한번 가보자 구경 좀 하고 와', ['explore'], []],
  ['집이 너무 좁은데 마을 하나 더 만들자', ['build:village'], []],
  ['성전 하나 멋지게 지어보자', ['build:temple'], []],
  ['율법파 애들이랑 친하게 지내면서 우리 편 좀 만들어봐', ['preach'], []],
  ['담벼락 좀 튼튼하게 올려놔, 쳐들어오면 큰일이야', ['build:wall'], []],
  ['추수철이 다가왔으니 익은 열매를 따서 곳간에 들여라', ['gather:food'], []],
  ['지붕을 새로 얹을 것이니 숲에서 목재를 구해오라', ['gather:wood'], []],
  ['다리를 놓을 것이니 바위산에서 돌을 좀 떠오라', ['gather:stone'], []],
  ['적이 날로 강성해지고 있으니 그들의 땅에 쳐들어가라', ['attack'], []],
  ['저들이 길을 잃고 헤매고 있으니 사랑으로 가르쳐 품어라', ['preach'], []],
  ['인구가 늘어 비좁으니 분가할 새 부락을 하나 일구어라', ['build:village'], []],
  ['감사할 일이 넘쳐나니 목청껏 찬송하라', ['pray'], []],
  ['우리는 아직 세상의 절반도 모르니 모험을 떠나라', ['explore'], []],
  ['신께 가까이 가고 싶은 이들이 많으니 예배당을 지어라', ['build:temple'], []],
  ['도적떼가 몰려온다 하니 요새를 견고히 쌓아 올려라', ['build:wall'], []],
  // '~지 말고'가 둘 — 둘 다 금지
  ['숲을 베지 말고 기도하지 말고 돌을 캐라', ['gather:stone', 'forbid:gather:wood', 'forbid:pray'], ['gather:wood', 'pray']],
];

const kindOf = (a) => (a.type === 'gather' ? `gather:${a.gather}` : a.type === 'build' ? `build:${a.build}` : a.type);
function state() {
  const s = E.createState({ mode: 'tutorial', seed: 1 });
  E.startRound(s);
  // 돌·목재가 있어야 성벽·마을 명령이 가능하다
  Object.assign(s.sides.player, { wood: 6, stone: 6, food: 6 });
  return s;
}
let ok = 0;
const rows = [];
for (const [text, want, avoid] of CASES) {
  const s = state();
  const r = I.interpretWithTablet(s, text);
  const kinds = r.orders.map(kindOf);
  const forb = r.forbidden.map((a) => `forbid:${kindOf(a)}`);
  const all = [...kinds, ...forb];
  const has = (w) => (w === 'gather:any' ? kinds.some((k) => k.startsWith('gather:')) : all.includes(w));
  const pass = want.every(has) && avoid.every((w) => !kinds.includes(w));
  if (pass) ok += 1;
  rows.push([pass ? 'O' : 'X', text, all.join(' ') || '(없음)', r.interpretation]);
}
for (const row of rows) if (process.argv.includes('--all') || row[0] === 'X') console.log(row.join(' | '));
console.log(`\n석판 이해: ${ok}/${CASES.length} (${Math.round((100 * ok) / CASES.length)}%)`);
